storage:
  dbPath: /data/mongodb/config/rs0

systemLog:
  destination: file
  path: /var/log/mongodb/test-cluster/cfg-0.log
  logAppend: true

processManagement:
  fork: true

net:
  tls:
    mode: requireTLS
    CAFile: /opt/mongodb/CA.pem
    certificateKeyFile: /opt/mongodb/member.pem

  bindIp: 127.0.0.1
  port: 57040

security:
  clusterAuthMode: x509
  authorization: enabled

replication:
  replSetName: cfg

sharding:
  clusterRole: configsvr
